In [30]:
from random import randint
import math
import pandas as pd
import numpy as np
import time

In [31]:
m = [1,2,3,4,5]
n = [1,2,3]
f = [5,10,8]
b = [20, 30, 25]
d = [10, 8, 15, 7, 12]

final = {"1":0,"2":0,"3":0,"4":0,"5":0,}
total = 0

mat = np.matrix([[2,3,4,5,7],[4,3,1,2,6],[5,4,2,1,3]])
print(mat)

mat2 = [2,3,4,5,7,4,3,1,2,6,5,4,2,1,3]
print(mat2)

[[2 3 4 5 7]
 [4 3 1 2 6]
 [5 4 2 1 3]]
[2, 3, 4, 5, 7, 4, 3, 1, 2, 6, 5, 4, 2, 1, 3]


In [32]:
def check_crom(crom):
    
    if sum(crom[:5]) <= 20 and sum(crom[5:10]) <= 30 and sum(crom[10:15]) <= 25 and crom[0]+crom[5]+crom[10]>=10 and crom[1]+crom[6]+crom[11]>=8 and crom[2]+crom[7]+crom[12]>=15 and crom[3]+crom[8]+crom[13]>=7 and crom[4]+crom[9]+crom[14]>=12:
    #if sum(crom[:5]) <= 20 and sum(crom[5:10]) <= 30 and sum(crom[10:15]) <= 25 and crom[0]+crom[5]+crom[10]==10 and crom[1]+crom[6]+crom[11]==8 and crom[2]+crom[7]+crom[12]==15 and crom[3]+crom[8]+crom[13]==7 and crom[4]+crom[9]+crom[14]==12:
        return True 
    else:
        return False 


In [33]:
def generar_crom(x): 
    cromosomas = [] 
    
    for i in range(x):
        salir = False
        
        while salir == False:
            crom = [randint(0,10),randint(0,8),randint(0,15),randint(0,7),randint(0,12),randint(0,10),randint(0,8),randint(0,15),randint(0,7),randint(0,12),randint(0,10),randint(0,8),randint(0,15),randint(0,7),randint(0,12)]
            
            if check_crom(crom):
                cromosomas.append(crom)
                salir = True
        
    return cromosomas


In [34]:
def fitness(poblacion,costos):
    
    calculo = 0
    
    for ii in range(len(poblacion)):
        calculo = 0
        
        for i,j in zip(poblacion[ii],costos): #calcualamos los costos multiplicando la matriz de cantidad de envio por la matriz de costos de enviar tal cantidad a tal cliente 
            calculo += i*j
        
        if sum(poblacion[ii][:5]) > 0: #checamos si se añaden costos fijos por aperturas de tiendas
            calculo += 20
        elif sum(poblacion[ii][5:10]) >0:
            calculo += 30
        elif sum(poblacion[ii][10:15]) >0:
            calculo += 25
            
        poblacion[ii].append(calculo)
        
    return poblacion


In [35]:
def selection(poblacion,tamaño):
    poblacion_sorteada = sorted(poblacion, key=lambda x:x[15]) #sortemos la lista de poblacinoes por costo
    
    return poblacion_sorteada[0:int(tamaño/2)]

In [36]:
def crossover(pob,tamaño):
    #agarar un padre y una madre aleatroios 
    #generar un hijo
    
    tam = len(pob)
    
    new_pob = []
    
    for i in range(tamaño):
        salir = False
        
        while salir == False:
            crom = pob[randint(0,tam-1)][:7] + pob[randint(0,tam-1)][7:15] #agarra uno mas de la madre que del padre 
            
            if check_crom(crom):
                new_pob.append(crom)
                salir = True
        
    return new_pob

In [37]:
def mutacion(pob):
    
    new_pob = []
    
    for i in range(len(pob)):
        salir = False
        
        while salir == False:
            crom = pob[i][:6] + [randint(0,8),randint(0,15),randint(0,7)] + pob[i][9:15]
            
            if check_crom(crom):
                new_pob.append(crom)
                salir = True 
                
    return new_pob

In [51]:
inicio = time.time()

tamaño = 100
poblacion = generar_crom(tamaño)
poblacion = fitness(poblacion,mat2)
poblacion_seleccionada = selection(poblacion, tamaño)
contador = 0

if poblacion_seleccionada[0][15] >= 102:
    salir = False

while salir == False:
    nueva_poblacion = crossover(poblacion_seleccionada, tamaño)
    nueva_poblacion = mutacion(nueva_poblacion)
    nueva_poblacion = fitness(nueva_poblacion,mat2)
    nueva_poblacion_seleccionada = selection(nueva_poblacion, tamaño)
    if nueva_poblacion_seleccionada[0][15] <= 170:
        print("Se Logro")
        print(nueva_poblacion_seleccionada[0])
        salir = True
    else:
        poblacion_seleccionada = nueva_poblacion_seleccionada
        contador += 1

fin = time.time()
print(" ")
print(f"Tiempo: {fin-inicio}")
print(f"Generacion {contador}")

Se Logro
[8, 4, 7, 0, 1, 0, 5, 3, 2, 1, 2, 0, 6, 5, 10, 168]
 
Tiempo: 0.3391098976135254
Generacion 3


In [60]:
inicio = time.time()

tamaño = 50
poblacion = generar_crom(tamaño)
poblacion = fitness(poblacion,mat2)
poblacion_seleccionada = selection(poblacion, tamaño) #sorteamos para conseguir la mitad de la poblacion que si nos interesa la "mejor"

nueva_poblacion = crossover(poblacion_seleccionada, tamaño)
nueva_poblacion = mutacion(nueva_poblacion)
nueva_poblacion = fitness(nueva_poblacion,mat2)
nueva_poblacion_seleccionada = selection(nueva_poblacion, tamaño)

if nueva_poblacion_seleccionada[0][15] <= 170:
    print("Se Logro")

tam = list(range(0, tamaño))

print("Poblacion Original")
for i,j in zip(poblacion[:5], tam[:5]):
    print(f"{j}: {i[0:15]} : {i[15]}")
    
print(" ")

print("Poblacion Seleccionada")
for i,j in zip(poblacion_seleccionada[:5], tam[:5]):
    print(f"{j}: {i[0:15]} : {i[15]}")

print(" ")

print("Nueva Poblacion")
for i,j in zip(nueva_poblacion[:5], tam[:5]):
    print(f"{j}: {i[0:15]} : {i[15]}")
    
print("Nueva Poblacion Seleccionada")
for i,j in zip(nueva_poblacion_seleccionada[:5], tam[:5]):
    print(f"{j}: {i[0:15]} : {i[15]}")
    
fin = time.time()
print(" ")
print(f"Tiempo: {fin-inicio}")

Poblacion Original
0: [0, 7, 1, 1, 7, 10, 0, 7, 5, 4, 3, 1, 11, 5, 4] : 238
1: [0, 5, 6, 1, 8, 8, 3, 7, 5, 2, 10, 0, 2, 2, 8] : 270
2: [9, 1, 2, 4, 1, 3, 7, 12, 2, 6, 1, 0, 2, 7, 5] : 192
3: [4, 0, 6, 7, 0, 8, 7, 7, 0, 7, 0, 8, 2, 6, 6] : 249
4: [1, 7, 4, 5, 3, 3, 5, 9, 0, 9, 7, 4, 3, 6, 3] : 267
 
Poblacion Seleccionada
0: [9, 1, 2, 4, 1, 3, 7, 12, 2, 6, 1, 0, 2, 7, 5] : 192
1: [10, 7, 0, 2, 1, 0, 3, 12, 7, 6, 1, 1, 8, 1, 8] : 199
2: [8, 2, 6, 3, 1, 0, 7, 11, 1, 3, 3, 0, 4, 4, 11] : 200
3: [1, 4, 4, 4, 2, 8, 3, 12, 4, 1, 1, 2, 7, 2, 9] : 207
4: [9, 4, 1, 4, 2, 1, 5, 14, 5, 3, 3, 1, 8, 2, 10] : 216
 
Nueva Poblacion
0: [8, 2, 6, 3, 1, 0, 7, 5, 6, 3, 3, 1, 8, 2, 10] : 211
1: [9, 1, 5, 4, 1, 4, 5, 10, 2, 2, 4, 5, 4, 1, 9] : 221
2: [10, 2, 5, 2, 1, 5, 0, 12, 2, 6, 1, 6, 6, 4, 6] : 218
3: [10, 7, 0, 2, 1, 0, 2, 11, 4, 3, 3, 0, 4, 4, 11] : 181
4: [10, 1, 1, 0, 7, 1, 4, 13, 1, 6, 0, 7, 11, 6, 1] : 222
Nueva Poblacion Seleccionada
0: [10, 7, 0, 2, 1, 0, 2, 11, 4, 3, 3, 0, 4, 4, 11] : 181
1: [